### ISSUE TITLE
dfuzzer fails to compile on Fedora 40

### ISSUE THREAD

**Issue by evverx** [dbus-fuzzer/dfuzzer#143]
https://download.copr.fedorainfracloud.org/results/packit/dbus-fuzzer-dfuzzer-142/fedora-40-aarch64/07396105-dfuzzer/builder-live.log.gz
```sh
../src/suppression.c:123:37: error: â€˜callocâ€™ sizes specified with â€˜sizeofâ€™ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
  123 |                 item = calloc(sizeof(*item), 1);
      |                                     ^
../src/suppression.c:123:37: note: earlier argument should specify number of elements, later size of each element
cc1: all warnings being treated as errors
```
(It failed in https://github.com/dbus-fuzzer/dfuzzer/pull/142)
